### ISSUE TITLE
Support Google OAuth

### ISSUE THREAD

**Issue by jonwinton** [clay/clay#3]
Google is dropping support for Google+ API. We need to provide support for the new auth method by the 21st of January.

## Details
- Update should be made in Amphora's auth module
- Need to find which [Passport.js](http://www.passportjs.org/) module will support
- Document configuration

**Comment by ncbooth** [comment]
Replacement for the google+ api: https://developers.google.com/identity/sign-in/web/

**Comment by manuelurenah** [comment]
Passport strategy for google oauth: http://www.passportjs.org/packages/passport-google-oauth/

**Comment by jonwinton** [comment]
Handled in https://github.com/clay/amphora/pull/626
